server:
  port: 8000

jwt:
  secret: javainuse
  lifetime: 3600

spring:
  datasource:
    url: jdbc:postgresql://db:5432/inside
    username: root
    password: rootroot
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      event:
        merge:
          entity_copy_observer: "allow"
      ddl-auto: validate

    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: update
              create-target: create.sql
              create-source: metadata

flyway:
  url: jdbc:postgresql://db:5432/inside
  user: root
  password: rootroot
  baseline-on-migrate: true